oauth:
  open-banking:
    key:
      client-id: 9afbb17b-a1c9-4a7c-b66f-98b6cf623fef
      client-secret: cb20df8b-5113-4373-8c13-45903ca7ecb5
    uri:
      redirect-uri: http://localhost:8080/api/account
      token-uri: https://testapi.openbanking.or.kr/oauth/2.0/token
